jobs:
  ci:
    name: Test
    runs-on: ubuntu-20.04

    steps:
      - name: Begin
        uses: actions/checkout@v2
      - name: Fetch Deps
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Run Tests
        run: ./check/main

name: Main

on:
  schedule:
    - cron: "0 1/3 * * *"
